### ISSUE TITLE
Deploy fails on "node-pre-gyp install --fallback-to-build"

### ISSUE THREAD

**Issue by doeni** [jpsim/AWSPics#8]
Hi there,

deploy fails with following error message (issue seems to be htpasswd-auth):

```
npm WARN package.json lambda-cloudfront-cookies@1.0.0 No repository field.
npm WARN package.json lambda-cloudfront-cookies@1.0.0 No README data
WARN engine apache-crypt@1.2.1: wanted: {"node":">=4.6.1"} (current: {"node":"4.3.2","npm":"2.14.12"})
WARN engine apache-md5@1.1.2: wanted: {"node":">=4.6.1"} (current: {"node":"4.3.2","npm":"2.14.12"})

> bcrypt@2.0.1 install /build/node_modules/htpasswd-auth/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/build/node_modules/htpasswd-auth/node_modules/bcrypt/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
node-pre-gyp ERR! stack     at Module.load (module.js:343:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:300:12)
node-pre-gyp ERR! stack     at Module.require (module.js:353:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/build/node_modules/htpasswd-auth/node_modules/bcrypt/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)
node-pre-gyp ERR! System Linux 4.9.87-linuxkit-aufs
node-pre-gyp ERR! command "/usr/local/lib64/node-v4.3.x/bin/node" "/build/node_modules/htpasswd-auth/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /build/node_modules/htpasswd-auth/node_modules/bcrypt
node-pre-gyp ERR! node -v v4.3.2
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/lib64/node-v4.3.x/bin/node" "/usr/local/lib64/node-v4.3.x/bin/npm" "install" "--save" "htpasswd-auth"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the bcrypt@2.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /build/npm-debug.log
The command '/bin/sh -c npm install --save htpasswd-auth' returned a non-zero code: 1
```

So i changed the dockerfile to:
```
FROM lambci/lambda-base:build

ENV PATH=/var/lang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib \
    AWS_EXECUTION_ENV=AWS_Lambda_nodejs8.10 \
    NODE_PATH=/var/runtime:/var/task:/var/runtime/node_modules \
    npm_config_unsafe-perm=true

RUN rm -rf /var/runtime /var/lang && \
  curl https://lambci.s3.amazonaws.com/fs/nodejs8.10.tgz | tar -zx -C /

CMD ["npm", "rebuild"]

RUN mkdir /build
WORKDIR /build
COPY package.json /build/package.json

RUN npm install --production

COPY index.js /build/index.js

RUN zip -r /build/dist.zip . > /dev/null
CMD ["cat", "/build/dist.zip"]
```

Which results in a finished deploy. Taking a look at the stack everything seems fine, but I'm unable to login with my credentials on the site.

**Comment by jpsim** [comment]
Have you tried following the instructions in the error log?

**Comment by jpsim** [comment]
A cursory search seems to indicate that you might be getting this due to using an older node.js version. Can you try with the latest node.js version?

**Comment by doeni** [comment]
That's what i did, then i ended up being unable to login with my credentials, so something went wrong with htpasswd-auth i guess. Was unable to find out more so far.

**Comment by doeni** [comment]
Now the reason the auth fails seems to be the now unexpected bcrypt version:

```
Response:
{
  "errorMessage": "Module version mismatch. Expected 46, got 57.",
  "errorType": "Error",
  "stackTrace": [
    "Object.Module._extensions..node (module.js:434:18)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/bcrypt/bcrypt.js:6:16)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)"
  ]
}

Request ID:
"300e94fc-5f59-11e8-b788-b5fee5d44857"

Function Logs:
START RequestId: 300e94fc-5f59-11e8-b788-b5fee5d44857 Version: $LATEST
module initialization error: Error
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
END RequestId: 300e94fc-5f59-11e8-b788-b5fee5d44857
REPORT RequestId: 300e94fc-5f59-11e8-b788-b5fee5d44857	Duration: 186.04 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 37 MB	
module initialization error
Error
```

**Comment by lczupryn** [comment]
Ok,

For me works using old bcrypt:
npm install bcrypt@0.8.7

Thanks for awesome work!

**Comment by doeni** [comment]
Mind sharing the whole part?

**Comment by jpsim** [comment]
Hi all, can you link me to the discussion you all started with bcrypt after following the instructions in the error log?

```
npm ERR! Failed at the bcrypt@2.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /build/npm-debug.log
The command '/bin/sh -c npm install --save htpasswd-auth' returned a non-zero code: 1
```

**Comment by mackay2k4** [comment]
Using the changed dockerfile @doeni provided works. But you also need to change the runtime environment of  the login lambda function to "nodejs8.10".

**Comment by lczupryn** [comment]
Hi,
I delete the previous post not to mislead anybody as far as I was facing some more issues.

The easiest way to fix that issue is to get the exactly htpasswd-auth package in version 2.0.0 cause even the minor change 2.0.1 is changing libraries bcrypt to bcryptjs.

Below code, i change in package.json

`{
  "name": "lambda-cloudfront-cookies",
  "version": "1.0.0",
  "description": "AWS Lambda function that creates CloudFront cookies for valid users",
  "author": "thumbsup",
  "license": "MIT",
  "main": "index.js",
  "dependencies": {
    "async": "^2.1.4",
    "aws-cloudfront-sign": "^2.2.0",
    "htpasswd-auth": "2.0.0"
  }
}`

**Comment by theBoEffect** [comment]
You can also just use the updated "FROM lambci/lambda:build-nodejs8.10" in the Dockerfile without any other changes, and then update the lambda runtimes as @mackay2k4 said.
